### ISSUE TITLE
Unexpected switch off

### ISSUE THREAD

**Issue by BB1982** [johnwargo/Seeed-Studio-Relay-Board#2]
When trying to activate and deactivate a single relay with an individual script, the relays that are already on do turn off without an explicit 'off' command.

**Comment by johnwargo** [comment]
OK, so it's been a really long time (three years) since I wrote that code, so I'm a little rusty. What I did was essentially take the Seeed sample code and make a library out of it.

The way the code works is it pokes and prods on a shared memory location between the Raspberry Pi and the relay board. I think the issue you're having is that when the code manipulates that memory location, it modifies the value incorrectly. I know that's vague, but that's what I think is happening.

For example, this code:

```c
DEVICE_REG_DATA &= ~(0x1 << (relay_num - 1))
```

Is doing binary ANDs and shifts of the device data on the board then writes it to the memory location. If your memory address for the board is wrong, or the number of ports is wrong (the two configuration values at the top of the file) then I imagine it wouldn't work at all, not work in a weird way like it is.

So I'm going to ask some silly questions:

1. Did you follow the instructions to set the number of relay ports for the board? the code sets it to 4, do you have a 4 relay board? I'm assuming yes and you've made no changes to this part of the code.
2. Did you set the memory address for the board correctly?

Take a look at the `relay_get_port_data` function - check its value after you turn a port on and off, it should reflect what's shown in the table on the module's readme file. If it doesn't, then that's where to look because everything the module does is related to manipulating the data returned by that function.

**Comment by BB1982** [comment]
At the end I found a solution to my problem: 
1. I modified the 'toggle port' function of the library so that it does now just the opposite to what it did originally, (switching on if the relay was off and vice-versa). Now the function checks the status of the port and switches on if the relay was on and vice-versa. I called this function 'keep_status(relay_num)'
2. I created individual scripts where I perform this sort of 'reversed toggle port' on all relays different than that I want to operate before the call to the function relay_on or relay_off.
The scripts now have the lines (example for relay 1):
keep_status(2)
keep_status(3)
keep_status(4)
relay_on(1)

or

keep_status(2)
keep_status(3)
keep_status(4)
relay_off(1)

Can't really explain why it works, but it does!

**Comment by johnwargo** [comment]
Well that's just weird - so the check port status is inverted? That doesn't make any sense as it worked for a long time. I'll dig out the hardware and give it a try.

**Comment by johnwargo** [comment]
@BB1982  I think the answer is in `relay_get_port_status`: 

```python
# return (DEVICE_REG_DATA & mask) != 0
return (self.DEVICE_REG_DATA & mask) == 0
```

I'm not sure why or when I made that change (yes, I know I could look), but I bet if you switch those it starts working like expected. If you have time, check it out and let me know and I'll update the code.

**Comment by johnwargo** [comment]
Yesterday, I created an updated version of the library,  you can find it here: https://github.com/johnwargo/seeed-studio-relay-v2. The new version enables you to initialize the library with the address for the relay board, so you can interact with more than one board in an app. I also created a new test program that adds exercising the toggle method to the test app.

Running it, everything works great, so I'm really not sure why you had this issue. Maybe flaky board?  I don't know. Closing this as there's nothing I can do here.
